<a href="https://colab.research.google.com/github/gitegg007/testrepo/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[Numpy-for mathematical calculations in Python](https://numpy.org/)

In [ ]:
!pip install numpy   #Local Environment

In [ ]:
#Create Numpy array
import numpy as np
ar=np.array([45,63,98,75,15,46,32,98])  #Single dim
#ar=np.array([45,63,98,75,15,46,32,98,45.36])
print(ar)
print(type(ar))
print(ar.dtype)
print(ar[5])  #indexing in 1D array

[45 63 98 75 15 46 32 98]
<class 'numpy.ndarray'>
int64
46


In [ ]:
#arange(start,stop,step)
ar=np.arange(10,20)
ar=np.arange(10,20,2)
print(ar)

[10 12 14 16 18]


In [ ]:
#linespace()
print(np.linspace(10,100,10))
print(np.linspace(10,100,5)) #Uniform Distribution

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
[ 10.   32.5  55.   77.5 100. ]


In [ ]:
#randint()
print(np.random.randint(1,100,10))

[39 22  8 85 88 38 74 22 80 17]


In [ ]:
#Identity Matrix
print(np.eye(5,dtype='int'))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [ ]:
#Create 2D array [rows,colms]
ar=np.array([[10,20,30,100],[40,50,60,200],[70,80,90,300]])
print(ar)
print("No of dims:",ar.ndim)
print("Shape:",ar.shape)  #rows,colmns
print("Size:",ar.size)
print("Data type:",ar.dtype)
print(ar[2][3])  #indexing in 2D [row][col]

[[ 10  20  30 100]
 [ 40  50  60 200]
 [ 70  80  90 300]]
No of dims: 2
Shape: (3, 4)
Size: 12
Data type: int64
300


In [ ]:
for i in ar:
  print(i)  #row wise results

[ 10  20  30 100]
[ 40  50  60 200]
[ 70  80  90 300]


In [ ]:
for i in np.nditer(ar):
  print(i)  #element wise results

10
20
30
100
40
50
60
200
70
80
90
300


In [ ]:
#Slicing[start:stop:step]
ar=np.arange(10,20)
print(ar)
print(ar[3:8])

[10 11 12 13 14 15 16 17 18 19]
[13 14 15 16 17]


In [ ]:
ar=np.array([[10,20,30,100],[40,50,60,200],[70,80,90,300]])
print(ar)
print(ar[1:3,2:4])  #slicing for rows and columns

[[ 10  20  30 100]
 [ 40  50  60 200]
 [ 70  80  90 300]]
[[ 60 200]
 [ 90 300]]
